sudo: required
services:
  - docker

before_install:
  - docker build -t mtsmachado8/docker-react -f Dockerfile.dev .

script: # -- --coverage so it doesnt hang
  - docker run mtsmachado8/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  # region is on aws's url. Right before .elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  # search for bucket_name typing s3(cloud service to deploy) on aws services
  bucket_name: "elasticbeanstalk-us-east-2-257844553213"
  # bucket_path is inside s3's bucket. Default defined as app's name
  bucket_path: "docker-react"
  # when to trigger the deploy
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY